# config for analysis

# most CPUs to ever use at once for a job
max_cpus: 16

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

# amplicons sequenced by PacBio
amplicons: data/PacBio_amplicons.gb

# how to parse the amplicon
feature_parse_specs: data/feature_parse_specs.yaml

# sequencing counts to cells ratio should exceed this for escape samples
escape_min_counts_to_cells_ratio: 2.5
# sequencing counts should exceed this for reference samples
reference_min_counts: 1e+7

# wildtype sequence of mutagenized gene
wildtype_sequence: data/wildtype_sequence.fasta
site_number_offset: 330  # add this to sequential sites to get RBD numbering

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0


# Parameters used when computed escape scores:
escape_score_type: frac_escape  # type of escape score, see dms_variants
escape_score_pseudocount: 0.5  # added to observed counts
escape_score_floor_E: 0  # floor on escape fractions
escape_score_ceil_E: 1  # ceiling on escape fractions
# Group variants by this when calculating escape scores; sensible values are
# "barcode" (to calculate a score for each barcoded variant) or
# "aa_substitutions" (to group all variants with same amino-acid substitutions):
escape_score_group_by: barcode
# How to group variants for homologs:
escape_score_homolog_group_by: aa_substitutions

#sets of homologs in plotting orders
targets_ordered:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - BM48-31
  - BtKY72
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS2c_MAP
  - SARS-CoV-2
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3

EurAf_extant:
  - BM48-31
  - BtKY72

SARS2_extant:
  - SARS-CoV-2
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  
SARS1_extant:
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084

Clade2_extant:
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3

ancestors_MAP:
  - AncSarbecovirus_MAP
  - AncAsia_MAP
  - AncSARS2a_MAP
  - GD-Pangolin
  - AncSARS2c_MAP
  - AncSARS1a_MAP
  - Rs7327
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncClade2_MAP
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  
ancestors_MAP_v_alt:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only

#antibodies in desired order for plotting
antibodies_ordered:
  - S309
  - S2X35
  - S2X259
  - S304
  - S2H97
  - S2H97_stringent
  - S2E12
  - S2H58
  - S2X16
  - S2D106
  - S2X58
  - S2H13
  - S2H13_stringent
  - S2H14
  - S2H14_stringent
  - S2X227

# Input files for analyses from the data subdirectory
sarbecovirus_alignment: data/RBD_aa_aligned.fasta


# output directories / files
summary_dir: results/summary
barcode_variant_table: data/barcode_variant_table.csv
barcode_expression: data/barcode_expression.csv
counts_dir: results/counts
variant_counts: results/counts/variant_counts.csv
escape_scores_dir: results/escape_scores
escape_fracs_barcodes: results/escape_scores/escape_scores_homolog_barcodes.csv
escape_fracs_homologs: results/escape_scores/escape_scores_homologs.csv
escape_muts: data/mutant_escape.csv
compare_mut_dir: results/compare_mut


